# Generated by Django 4.0.5 on 2022-06-23 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ijara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manzil', models.CharField(max_length=150)),
                ('lokatsiya', models.CharField(max_length=150)),
                ('malumot', models.TextField()),
                ('ism', models.CharField(max_length=150)),
                ('telefon', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('ijaranarxi', models.CharField(max_length=150)),
                ('rasm', models.FileField(blank=True, upload_to='media/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
